services:
  - type: web
    name: fashion-store
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: NEXT_PUBLIC_SOCKET_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: VNPAY_TMN_CODE
        sync: false
      - key: VNPAY_HASH_SECRET
        sync: false
      - key: VNPAY_URL
        value: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - key: VNPAY_RETURN_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
        sync: false
      - key: RESEND_API_KEY
        sync: false
